services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./templates:/app/templates
      - ./static/outputs:/app/static/outputs
    environment:
      - FLASK_APP=app.main
      - FLASK_DEBUG=1
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G
    tmpfs:
      - /dev/shm:size=512M